site_name: Multi-Way Algorithms
theme: readthedocs
repo_url: https://github.com/waikato-datamining/multiway-algorithms
site_description: Multiway Algorithms Documentation
pages:
    - Home: index.md
    - Algorithms:
      - PARAFAC: algorithms/algorithms.md
    - Stopping Criteria: stopping.md
    - Data: data.md