site_name: Multi-Way Algorithms
theme: readthedocs
repo_url: https://github.com/waikato-datamining/multiway-algorithms
site_description: Multiway Algorithms Documentation
pages:
    - Home: index.md
    - Algorithms:
      - PARAFAC: algorithms/parafac.md
      - Multilinear PLS: algorithms/npls.md
      - Non-Negative Tensor Factorization: algorithms/ntf.md
    - Stopping Criteria: stopping.md
    - Data: data.md